deluge:
  labels:
    - name: tv-sonarr
      javaAge: 3d
      removeData: true
    - name: radarr
      javaAge: 3d
      removeData: true
    - name: audiobooks
      javaAge: 30d
      removeData: false
