[versions]
activity-compose = "1.7.2"
agp = "8.2.0-alpha07"
androidx-test-ext-junit = "1.1.5"
compose-bom = "2023.05.01"
core-ktx = "1.10.1"
espresso-core = "3.5.1"
junit = "4.13.2"
kotlin = "1.8.10"
lifecycle-runtime-ktx = "2.6.1"
spring-boot = "3.1.0"
spring-dependency-management = "1.1.0"
sqlite = "3.42.0.0"

[libraries]
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
material3 = { group = "androidx.compose.material3", name = "material3" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect" }
spring-boot-starter-web = { group = "org.springframework.boot", name = "spring-boot-starter-web"}
spring-boot-starter-data-jpa = { group = "org.springframework.boot", name = "spring-boot-starter-data-jpa"}
sqlite = { group = "org.xerial", name = "sqlite-jdbc", version.ref = "sqlite"}
sqlite-dialect = { group = "org.hibernate.orm", name = "hibernate-community-dialects"}

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
spring-boot =  { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management =  { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }

[bundles]

